// --- START OF FILE PrescriptionOrder.cs ---

using UnityEngine; // Needed for [SerializeField] and [Tooltip]
using System; // Needed for System.Serializable

namespace Game.Prescriptions // A new namespace for prescription-related systems
{
    /// <summary>
    /// Represents a single prescription order generated by the PrescriptionManager.
    /// Now includes a calculated money worth. // <-- Added note about money worth
    /// </summary>
    [System.Serializable] // Make this struct serializable so it can be used in inspector lists
    public struct PrescriptionOrder // Using a struct for a simple data container
    {
        [Tooltip("The name of the patient for this prescription.")]
        public string patientName;

        [Tooltip("The name or identifier of the prescribed drug.")]
        public string prescribedDrug; // Could be an ItemDetails reference or ID later

        [Tooltip("How many times per day the dose should be taken.")]
        public int dosePerDay; // Renamed slightly for clarity

        [Tooltip("The total number of days the treatment should last.")]
        public int lengthOfTreatmentDays; // Renamed slightly for clarity

        [Tooltip("Flag indicating if this is an illegal or suspicious order (for later).")]
        public bool illegalOrder;

        // --- NEW FIELD: Money Worth ---
        [Tooltip("The calculated monetary value of this prescription order.")]
        [SerializeField] // Serialize for inspector visibility/saving
        public float moneyWorth; // Use float for potential decimal values
        // --- END NEW FIELD ---


        // Optional: Add a constructor for easier initialization
        // --- MODIFIED CONSTRUCTOR to include moneyWorth ---
        public PrescriptionOrder(string patientName, string prescribedDrug, int dosePerDay, int lengthOfTreatmentDays, bool illegalOrder = false, float moneyWorth = 0f)
        {
            this.patientName = patientName;
            this.prescribedDrug = prescribedDrug;
            this.dosePerDay = dosePerDay;
            this.lengthOfTreatmentDays = lengthOfTreatmentDays;
            this.illegalOrder = illegalOrder;
            this.moneyWorth = moneyWorth; // Initialize the new field
        }
        // --- END MODIFIED CONSTRUCTOR ---


        // Optional: Override ToString for easier debugging
        // --- MODIFIED ToString to include moneyWorth ---
        public override string ToString()
        {
            return $"PrescriptionOrder [Patient: {patientName}, Drug: {prescribedDrug}, Dose: {dosePerDay}/day, Length: {lengthOfTreatmentDays} days, Illegal: {illegalOrder}, Worth: ${moneyWorth:F2}]"; // Added moneyWorth, formatted to 2 decimal places
        }
        // --- END MODIFIED ToString ---
    }
}

// --- END OF FILE PrescriptionOrder.cs ---